### ISSUE TITLE
App doesn't work on latest python 3.11.1

### ISSUE THREAD

**Issue by ghost** [rytilahti/python-songpal#125]
Python 3.11.1
pip 22.3.1

```
PS C:\Users\username> pip install python-songpal

PS C:\Users\username> songpal
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\username\scoop\apps\python\current\Scripts\songpal.exe\__main__.py", line 4, in <module>
  File "C:\Users\username\scoop\apps\python\current\Lib\site-packages\songpal\main.py", line 115, in <module>
    @coro
     ^^^^
  File "C:\Users\username\scoop\apps\python\current\Lib\site-packages\songpal\main.py", line 43, in coro
    f = asyncio.coroutine(f)
        ^^^^^^^^^^^^^^^^^
AttributeError: module 'asyncio' has no attribute 'coroutine'. Did you mean: 'coroutines'?
```

**Comment by krakhimov** [comment]
Here are patch file with fix
[Changes-On-dc437c.patch](https://github.com/rytilahti/python-songpal/files/10322842/Changes-On-dc437c.patch)

**Comment by rytilahti** [comment]
If you don't mind installing the git installation, could you try to see if that works? https://github.com/rytilahti/python-songpal/pull/121 should have fixed the issue but as no one reported back I was hesitant to make a release if that does not fix it...

**Comment by kdw2060** [comment]
Hi, i'd like to test this, but what should I do for 'installing the git installation', that's unclear to me.

**Comment by rytilahti** [comment]
Hi, just install it with pip like this:
```
pip install git+https://github.com/rytilahti/python-songpal.git
```
and you can then use the `songpal` command as usual. Thanks for testing :-)

**Comment by kdw2060** [comment]
The error message that krakhimov posted (and I had too) is gone indeed.

I still get another error when trying to discover my device, but I think that's probably due to my device not being supported anymore by Sony in the latest version of their api (STR-DN850).
```ERROR:songpal.discovery:Unable to find X_ScalaerWebAPI_DeviceInfo```

**Comment by rytilahti** [comment]
Okay, that's unfortunate, thanks for testing and reporting back though :-( Btw, looks like they list that device also at https://vssupport.sony.net/en_ww/device.html as not supported.

I created a new release 0.15.2 so this issue can be closed now.
